// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/pb/snow.proto

package snow_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IDRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDRequest) Reset()         { *m = IDRequest{} }
func (m *IDRequest) String() string { return proto.CompactTextString(m) }
func (*IDRequest) ProtoMessage()    {}
func (*IDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1782e4024ab5503, []int{0}
}

func (m *IDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDRequest.Unmarshal(m, b)
}
func (m *IDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDRequest.Marshal(b, m, deterministic)
}
func (m *IDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDRequest.Merge(m, src)
}
func (m *IDRequest) XXX_Size() int {
	return xxx_messageInfo_IDRequest.Size(m)
}
func (m *IDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IDRequest proto.InternalMessageInfo

func (m *IDRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type IDResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDResponse) Reset()         { *m = IDResponse{} }
func (m *IDResponse) String() string { return proto.CompactTextString(m) }
func (*IDResponse) ProtoMessage()    {}
func (*IDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1782e4024ab5503, []int{1}
}

func (m *IDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDResponse.Unmarshal(m, b)
}
func (m *IDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDResponse.Marshal(b, m, deterministic)
}
func (m *IDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDResponse.Merge(m, src)
}
func (m *IDResponse) XXX_Size() int {
	return xxx_messageInfo_IDResponse.Size(m)
}
func (m *IDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IDResponse proto.InternalMessageInfo

func (m *IDResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type IDsRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDsRequest) Reset()         { *m = IDsRequest{} }
func (m *IDsRequest) String() string { return proto.CompactTextString(m) }
func (*IDsRequest) ProtoMessage()    {}
func (*IDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1782e4024ab5503, []int{2}
}

func (m *IDsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDsRequest.Unmarshal(m, b)
}
func (m *IDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDsRequest.Marshal(b, m, deterministic)
}
func (m *IDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDsRequest.Merge(m, src)
}
func (m *IDsRequest) XXX_Size() int {
	return xxx_messageInfo_IDsRequest.Size(m)
}
func (m *IDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IDsRequest proto.InternalMessageInfo

func (m *IDsRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *IDsRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type IDsResponse struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDsResponse) Reset()         { *m = IDsResponse{} }
func (m *IDsResponse) String() string { return proto.CompactTextString(m) }
func (*IDsResponse) ProtoMessage()    {}
func (*IDsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1782e4024ab5503, []int{3}
}

func (m *IDsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDsResponse.Unmarshal(m, b)
}
func (m *IDsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDsResponse.Marshal(b, m, deterministic)
}
func (m *IDsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDsResponse.Merge(m, src)
}
func (m *IDsResponse) XXX_Size() int {
	return xxx_messageInfo_IDsResponse.Size(m)
}
func (m *IDsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IDsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IDsResponse proto.InternalMessageInfo

func (m *IDsResponse) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *IDsResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StatsRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsRequest) Reset()         { *m = StatsRequest{} }
func (m *StatsRequest) String() string { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()    {}
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1782e4024ab5503, []int{4}
}

func (m *StatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsRequest.Unmarshal(m, b)
}
func (m *StatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsRequest.Marshal(b, m, deterministic)
}
func (m *StatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsRequest.Merge(m, src)
}
func (m *StatsRequest) XXX_Size() int {
	return xxx_messageInfo_StatsRequest.Size(m)
}
func (m *StatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatsRequest proto.InternalMessageInfo

func (m *StatsRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type StatsResponse struct {
	DataCenterId         int64    `protobuf:"varint,1,opt,name=data_center_id,json=dataCenterId,proto3" json:"data_center_id,omitempty"`
	WorkerId             int64    `protobuf:"varint,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	StartTimestamp       int64    `protobuf:"varint,3,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	LastTimestamp        int64    `protobuf:"varint,4,opt,name=last_timestamp,json=lastTimestamp,proto3" json:"last_timestamp,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Sequence             int64    `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SequenceOverload     int64    `protobuf:"varint,7,opt,name=sequence_overload,json=sequenceOverload,proto3" json:"sequence_overload,omitempty"`
	ErrorsCount          int64    `protobuf:"varint,8,opt,name=errors_count,json=errorsCount,proto3" json:"errors_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1782e4024ab5503, []int{5}
}

func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (m *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(m, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetDataCenterId() int64 {
	if m != nil {
		return m.DataCenterId
	}
	return 0
}

func (m *StatsResponse) GetWorkerId() int64 {
	if m != nil {
		return m.WorkerId
	}
	return 0
}

func (m *StatsResponse) GetStartTimestamp() int64 {
	if m != nil {
		return m.StartTimestamp
	}
	return 0
}

func (m *StatsResponse) GetLastTimestamp() int64 {
	if m != nil {
		return m.LastTimestamp
	}
	return 0
}

func (m *StatsResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *StatsResponse) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *StatsResponse) GetSequenceOverload() int64 {
	if m != nil {
		return m.SequenceOverload
	}
	return 0
}

func (m *StatsResponse) GetErrorsCount() int64 {
	if m != nil {
		return m.ErrorsCount
	}
	return 0
}

func init() {
	proto.RegisterType((*IDRequest)(nil), "snow.pb.IDRequest")
	proto.RegisterType((*IDResponse)(nil), "snow.pb.IDResponse")
	proto.RegisterType((*IDsRequest)(nil), "snow.pb.IDsRequest")
	proto.RegisterType((*IDsResponse)(nil), "snow.pb.IDsResponse")
	proto.RegisterType((*StatsRequest)(nil), "snow.pb.StatsRequest")
	proto.RegisterType((*StatsResponse)(nil), "snow.pb.StatsResponse")
}

func init() { proto.RegisterFile("grpc/pb/snow.proto", fileDescriptor_a1782e4024ab5503) }

var fileDescriptor_a1782e4024ab5503 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x5f, 0x6b, 0xe2, 0x40,
	0x10, 0xc0, 0x49, 0x72, 0x46, 0x33, 0x6a, 0xce, 0xdb, 0xf3, 0x8e, 0x90, 0xf3, 0x41, 0x83, 0xc7,
	0x09, 0x07, 0x4a, 0x2b, 0x2d, 0x7d, 0x57, 0x28, 0x79, 0x69, 0x21, 0xf6, 0x3d, 0xac, 0xc9, 0xb6,
	0x04, 0x35, 0x9b, 0xee, 0xae, 0xb5, 0xdf, 0xa9, 0xfd, 0x90, 0x65, 0x77, 0x13, 0xff, 0x14, 0xea,
	0xdb, 0xce, 0x6f, 0x7e, 0x33, 0xc9, 0xee, 0x0c, 0xa0, 0x27, 0x56, 0x24, 0x93, 0x62, 0x39, 0xe1,
	0x39, 0xdd, 0x8d, 0x0b, 0x46, 0x05, 0x45, 0x75, 0x7d, 0x5e, 0x06, 0x03, 0x70, 0xc2, 0x79, 0x44,
	0x9e, 0xb7, 0x84, 0x0b, 0xd4, 0x85, 0x9a, 0xa0, 0x2b, 0x92, 0x7b, 0x46, 0xdf, 0x18, 0x39, 0x91,
	0x0e, 0x82, 0x1e, 0x80, 0x54, 0x78, 0x41, 0x73, 0x4e, 0x90, 0x0b, 0x66, 0x96, 0x2a, 0xc1, 0x8a,
	0xcc, 0x2c, 0x0d, 0x6e, 0x64, 0x96, 0x9f, 0xed, 0x20, 0x69, 0x42, 0xb7, 0xb9, 0xf0, 0x4c, 0x55,
	0xa6, 0x83, 0xe0, 0x0a, 0x9a, 0xaa, 0xb2, 0x6c, 0xdc, 0x01, 0x2b, 0x4b, 0xb9, 0x67, 0xf4, 0xad,
	0x91, 0x15, 0xc9, 0xe3, 0x17, 0x65, 0x43, 0x68, 0x2d, 0x04, 0x16, 0xe7, 0x3f, 0x19, 0xbc, 0x9b,
	0xd0, 0x2e, 0xb5, 0xb2, 0xff, 0x10, 0xdc, 0x14, 0x0b, 0x1c, 0x27, 0x24, 0x17, 0x84, 0xc5, 0xfb,
	0x4b, 0xb4, 0x24, 0x9d, 0x29, 0x18, 0xa6, 0xe8, 0x0f, 0x38, 0x3b, 0xca, 0x56, 0x5a, 0xd0, 0xdf,
	0x6d, 0x68, 0x10, 0xa6, 0xe8, 0x1f, 0x7c, 0xe7, 0x02, 0x33, 0x11, 0x8b, 0x6c, 0x43, 0xb8, 0xc0,
	0x9b, 0xc2, 0xb3, 0x94, 0xe2, 0x2a, 0xfc, 0x50, 0x51, 0xf4, 0x17, 0xdc, 0x35, 0xe6, 0xc7, 0xde,
	0x37, 0xe5, 0xb5, 0x25, 0x3d, 0x68, 0x3d, 0x70, 0x0e, 0x46, 0x4d, 0x19, 0x07, 0x80, 0x7c, 0x68,
	0x70, 0x79, 0xc7, 0x3c, 0x21, 0x9e, 0xad, 0xff, 0xa4, 0x8a, 0xd1, 0x7f, 0xf8, 0x51, 0x9d, 0x63,
	0xfa, 0x42, 0xd8, 0x9a, 0xe2, 0xd4, 0xab, 0x2b, 0xa9, 0x53, 0x25, 0xee, 0x4b, 0x8e, 0x06, 0xd0,
	0x22, 0x8c, 0x51, 0xc6, 0x63, 0xfd, 0x9c, 0x0d, 0xe5, 0x35, 0x35, 0x9b, 0x49, 0x74, 0xf9, 0x66,
	0x80, 0xb3, 0xc8, 0xe9, 0xee, 0x71, 0x8d, 0x57, 0x04, 0x5d, 0x80, 0x7d, 0x47, 0x5e, 0x45, 0x38,
	0x47, 0x68, 0x5c, 0x2e, 0xca, 0x78, 0xbf, 0x25, 0xfe, 0xcf, 0x13, 0x56, 0xbe, 0xee, 0x14, 0xec,
	0x5b, 0x22, 0xc2, 0x39, 0x47, 0xc7, 0xe9, 0x6a, 0x48, 0x7e, 0xf7, 0x14, 0x96, 0x45, 0xd7, 0x50,
	0x53, 0x33, 0x42, 0xbf, 0xf6, 0xe9, 0xe3, 0xd1, 0xfa, 0xbf, 0x3f, 0x63, 0x5d, 0xb7, 0xb4, 0xd5,
	0x12, 0x4f, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x58, 0x24, 0xa7, 0xda, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SnowflakeClient is the client API for Snowflake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SnowflakeClient interface {
	NextID(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*IDResponse, error)
	GetIDs(ctx context.Context, in *IDsRequest, opts ...grpc.CallOption) (*IDsResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type snowflakeClient struct {
	cc *grpc.ClientConn
}

func NewSnowflakeClient(cc *grpc.ClientConn) SnowflakeClient {
	return &snowflakeClient{cc}
}

func (c *snowflakeClient) NextID(ctx context.Context, in *IDRequest, opts ...grpc.CallOption) (*IDResponse, error) {
	out := new(IDResponse)
	err := c.cc.Invoke(ctx, "/snow.pb.Snowflake/NextID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snowflakeClient) GetIDs(ctx context.Context, in *IDsRequest, opts ...grpc.CallOption) (*IDsResponse, error) {
	out := new(IDsResponse)
	err := c.cc.Invoke(ctx, "/snow.pb.Snowflake/GetIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snowflakeClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/snow.pb.Snowflake/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnowflakeServer is the server API for Snowflake service.
type SnowflakeServer interface {
	NextID(context.Context, *IDRequest) (*IDResponse, error)
	GetIDs(context.Context, *IDsRequest) (*IDsResponse, error)
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
}

// UnimplementedSnowflakeServer can be embedded to have forward compatible implementations.
type UnimplementedSnowflakeServer struct {
}

func (*UnimplementedSnowflakeServer) NextID(ctx context.Context, req *IDRequest) (*IDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextID not implemented")
}
func (*UnimplementedSnowflakeServer) GetIDs(ctx context.Context, req *IDsRequest) (*IDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIDs not implemented")
}
func (*UnimplementedSnowflakeServer) Stats(ctx context.Context, req *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stats not implemented")
}

func RegisterSnowflakeServer(s *grpc.Server, srv SnowflakeServer) {
	s.RegisterService(&_Snowflake_serviceDesc, srv)
}

func _Snowflake_NextID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeServer).NextID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snow.pb.Snowflake/NextID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeServer).NextID(ctx, req.(*IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snowflake_GetIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeServer).GetIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snow.pb.Snowflake/GetIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeServer).GetIDs(ctx, req.(*IDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snowflake_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snow.pb.Snowflake/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Snowflake_serviceDesc = grpc.ServiceDesc{
	ServiceName: "snow.pb.Snowflake",
	HandlerType: (*SnowflakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NextID",
			Handler:    _Snowflake_NextID_Handler,
		},
		{
			MethodName: "GetIDs",
			Handler:    _Snowflake_GetIDs_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Snowflake_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/pb/snow.proto",
}
